# Generated by Django 2.2.6 on 2020-11-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_auto_20191030_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_image',
            field=models.ImageField(default='default2.jpg', upload_to='images/'),
        ),
    ]
